// Redux Action Types

export const ACTION_ERROR = 'ACTION_ERROR';
export const ASK_QUESTION_FIRE = 'ASK_QUESTION_FIRE';
export const UPDATE_HOME_SEARCH_BOX = 'UPDATE_HOME_SEARCH_BOX';

export const SET_QUESTION_VALUE = 'SET_QUESTION_VALUE';
