// Redux Action Types

export const ACTION_ERROR = 'ACTION_ERROR';
export const ASK_QUESTION_FIRE = 'ASK_QUESTION_FIRE';
export const UPDATE_HOME_SEARCH_BOX = 'UPDATE_HOME_SEARCH_BOX';

export const SET_QUESTION_VALUE = 'SET_QUESTION_VALUE';

export const USER_LOGIN_FIRE = 'USER_LOGIN_FIRE';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
